services:
  postgres:
    image: 'postgres:15'
    env_file:
      - .mvn/.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - '5432'

volumes:
  pgdata:
    driver: local
