mail.credentials:
  auth-method: basic
  username: user
  password: qwerty

spring:
#  docker.compose.skip.in-tests: false
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
#    password: ${POSTGRES_PASSWORD:postgres}
#    username: ${POSTGRES_USER:postgres}

#logging.level:
#  web: trace
#  org.springframework.web: trace
#  org.apache: trace

server.port: 8091
