name: Build

# описание события, по которому будет запускаться наш скрипт
on:
  # этот workflow нужно запускать при создании пулл-реквестов
  pull_request.branches:
    - '*'
  # и при каждом пуше в мастер
  push.branches:
    - 'master'

jobs.build:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v1
    - name: set up JDK @21
      uses: actions/setup-java@v21
      with.java-version: 21
    - name: Maven Package
      run: mvn -B clean package -DskipTests
